server:
  port: 4006
spring:
  application:
    name: livegoods-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # 定义banner的路由
        - id: banner
#          uri: lb://livegoods-banner
          uri: http://127.0.0.1:9000
          predicates:
            - Path=/banner
        # 定义commendation的路由
        - id: recommendation
          uri: http://127.0.0.1:9001
          predicates:
            - Path=/recommendation
            - Query=city #请求参数必须含city参数
        # 定义hotproduct的路由
        - id: hotproduct
          uri: http://127.0.0.1:9002
          predicates:
            - Path=/hotProduct
            - Query=city #请求参数必须含city参数
        # 定义search的路由
        - id: search
          uri: http://127.0.0.1:9003
          predicates:
            - Path=/search
            - Query=city #请求参数必须含city参数
            - Query=content
            - Query=page #只能处理get请求参数
        # 定义details的路由
        - id: details
          uri: http://127.0.0.1:9004
          predicates:
            - Path=/details
            - Query=id
        # 定义comments的路由
        - id: comments
          uri: http://127.0.0.1:9005
          predicates:
            - Path=/comment
            - Query=id
            - Query=page
        # 定义buytime的路由
        - id: buytime
          uri: http://127.0.0.1:9006
          predicates:
            - Path=/buytime
            - Query=id
        # 定义登陆的路由
        - id: passport
          uri: http://127.0.0.1:9007
          predicates:
            - Path=/sendyzm,/login
        - id: buyaction
          uri: http://127.0.0.1:9009
          predicates:
            - Path=/buyaction
            - Query=id
            - Query=user
        - id: order
          uri: http://127.0.0.1:9008
          predicates:
            - Path=/order
            - Query=user
        - id: feedback
          uri: http://127.0.0.1:9010
          predicates:
            - Path=/feelback
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      register-with-eureka: true